service: damian-lambda-test # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  getTest:
    handler: handler.getTest
    events:
      - http:
          path: /gettest
          method: get
  postTest:
    handler: handler.postTest
    events:
      - http:
          path: /posttest
          method: post
          cors: true
          integration: LAMBDA
          request:
          template:
            application/json: '{ "httpMethod" : "$context.httpMethod"  }'
